# Generated by Django 5.2.3 on 2025-07-04 13:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parking', '0001_initial'),
        ('vehicles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingarea',
            name='owner',
            field=models.ForeignKey(limit_choices_to={'user_type': 'owner'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='parkingguard',
            name='guard_user',
            field=models.ForeignKey(limit_choices_to={'user_type': 'guard'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='parkingguard',
            name='parking_area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parking.parkingarea'),
        ),
        migrations.AddField(
            model_name='vehicleinfo',
            name='parking_area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='parking.parkingarea', verbose_name='Parking Area'),
        ),
        migrations.AddField(
            model_name='vehicleinfo',
            name='vehicle_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicles.vehicletype', verbose_name='Vehicle Type'),
        ),
    ]
