# Generated by Django 5.2.3 on 2025-07-22 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_username_alter_user_email'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('admin', 'Admin'), ('owner', 'Parking Owner'), ('customer', 'Customer'), ('guard', 'Guard')], default='admin', verbose_name='Role'),
        ),
    ]
