# Generated by Django 5.2.3 on 2025-07-09 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicletype',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
