# Generated by Django 5.2.3 on 2025-07-10 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingbooking',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
